name: Flutter Build iOS (No IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq (manual for macOS)
        run: brew install yq

      - name: Get pubspec version
        id: get_flutter_app_version
        run: |
          VERSION=$(yq '.version' pubspec.yaml | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Building iOS
        run: flutter build ios --release

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-output-ios
          path: build/ios/iphoneos
