name: Flutter Build iOS IPA (Basic Build) # اسم الـ Workflow

on:
  push:
    branches:
      - main # هيشتغل لما تعمل Push على main
  workflow_dispatch # هيشتغل يدوي

jobs:
  build:
    runs-on: macos-latest # لازم يشتغل على Mac عشان يبني iOS

    steps:
      - name: Checkout repository # سحب كود المشروع
        uses: actions/checkout@v3

      # تم إزالة الخطوات المتعلقة بتثبيت الشهادات والبروفيجن بروفايل والـ Secrets

      - name: Install yq # تثبيت أداة yq لقراءة ملفات YAML
        uses: mikefarah/yq@v4.42.1

      - name: Get pubspec version # استخلاص رقم الإصدار من pubspec.yaml
        id: get_flutter_app_version
        run: |
          VERSION=$(yq '.version' pubspec.yaml | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_OUTPUT # حفظ رقم الإصدار كـ output

      - name: Install Flutter # تثبيت Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # استخدام قناة Stable

      - name: Get Flutter dependencies # جلب الـ Packages
        run: flutter pub get

      - name: Building IPA # <<< محاولة بناء ملف الـ IPA - الخطوة دي هتتطلب Code Signing اللي مش متوفر هنا بشكل سليم >>>
        run: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
        # NOTE: This step is highly likely to fail due to missing code signing identities/provisioning profiles,
        # as they are NOT being installed by this simplified workflow.
        # If it doesn't fail outright, the resulting IPA will likely be unsigned or invalid.


      - name: Save potential IPA artifact # حفظ أي ملف IPA قد ينتج عن خطوة البناء (قد يكون غير كامل أو غير صالح)
        uses: actions/upload-artifact@v3
        with:
          name: build-output-ipa # اسم الـ Artifact
          path: build/ios/ipa/*.ipa # المسار المتوقع لملف الـ IPA

      # تم إزالة خطوة التنظيف (لأن مفيش حاجة حساسة تم تثبيتها في هذا الـ Workflow)
      # تم إزالة الـ Job الخاص برفع Firebase
