name: Flutter Build iOS IPA (Basic Build)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Steps for installing certificates and provisioning profiles are removed as requested.

      - name: Install yq
        uses: mikefarah/yq@v4.42.1

      - name: Get pubspec version
        id: get_flutter_app_version
        run: |
          VERSION=$(yq '.version' pubspec.yaml | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Building IPA
        run: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
        # NOTE: This step is highly likely to fail due to missing code signing identities/provisioning profiles.
        # If it doesn't fail outright, the resulting IPA will likely be unsigned or invalid.

      - name: Save potential IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-ipa
          path: build/ios/ipa/*.ipa

      # Cleanup step is removed.
      # Firebase release job is removed.
